FROM python:3.10-slim

WORKDIR /app

# Copy root level models
COPY models.py .

# Copy admin & scanner app
COPY admin_scanner_app/ ./admin_scanner_app/

# Install dependencies
WORKDIR /app/admin_scanner_app
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5001

# Run app
CMD ["gunicorn", "--bind", "0.0.0.0:5001", "--workers", "2", "--timeout", "60", "app:app"]
